name: Publish OSSRH
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - id: install-secret-key
        name: Install gpg secret key
        run: cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
      - name: Grant Permission to Execute
        run: chmod +x gradlew
      - name: Publish Library
        env:
          ossrhUser: ${{ secrets.OSSRH_USER }}
          ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
        run: ./gradlew uploadArchives -Psigning.secretKeyRingFile=/home/runner/.gnupg/secring.gpg -Psigning.keyId=${{ secrets.OSSRH_GPG_KEY_ID }} -Psigning.password=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}